#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: firefly-tokens-erc1155
  description: ERC1155 token integration
  homepage: https://github.com/hyperledger-labs/firefly-tokens-erc1155
  default_branch: main
  has_downloads: true
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
